### ISSUE TITLE
Broken pycrc

### ISSUE THREAD

**Issue by steakunderscore** [twe4ked/dotfiles#5]
Hey, I'm just working with your pryrc file and have found an issue:

Basically you are over writing `Pry.config.print` with a new `proc`, but you aren't taking care of all the args. See [your pryrc](https://github.com/twe4ked/dotfiles/blob/master/config/pryrc#L35).

Basically in [pry.rb](https://github.com/pry/pry/blob/master/lib/pry.rb#L20) there is an extra parameter of `_pry_` being passed in. Which I think is the cause of a [bug that was raised](https://github.com/pry/pry/issues/1265) in pry

I was thinking to fix the issue, one of the following could be done, but I don't know enough about pry's config to be sure what is best.

Either just add the extra param:
```diff
diff --git a/config/pryrc b/config/pryrc
index f39d357..5b5caa8 100644
--- a/config/pryrc
+++ b/config/pryrc
@@ -32,13 +32,13 @@ end
 
 # use awesome print for output if available
 original_print = Pry.config.print
-Pry.config.print = proc do |output, value|
+Pry.config.print = proc do |output, value, *args|
   begin
     require 'awesome_print'
     value = value.to_a if defined?(ActiveRecord) && value.is_a?(ActiveRecord::Relation)
     output.puts value.ai
   rescue LoadError => err
-    original_print.call(output, value)
+    original_print.call(output, value, args)
   end
 end
```

Or how about just setting the default printer when awesome print can't be loaded?
```diff
diff --git a/config/pryrc b/config/pryrc
index f39d357..c8d5f75 100644
--- a/config/pryrc
+++ b/config/pryrc
@@ -31,15 +31,14 @@ old_winch = trap 'WINCH' do
 end
 
 # use awesome print for output if available
-original_print = Pry.config.print
-Pry.config.print = proc do |output, value|
-  begin
-    require 'awesome_print'
+begin
+  require 'awesome_print'
+  Pry.config.print = proc do |output, value|
     value = value.to_a if defined?(ActiveRecord) && value.is_a?(ActiveRecord::Relation)
     output.puts value.ai
-  rescue LoadError => err
-    original_print.call(output, value)
   end
+rescue LoadError => err
+  Pry.config.print = Pry::DEFAULT_PRINT
 end
```
I think that this second option would mean not raising and catching an exception every time something is printed when awesome print isn't installed. But would seem to lock you to using `Pry::DEFAULT_PRINT` maybe?

Anyway, let me know what you think. I would be happy to send you a pull request if you like any of these options.

**Comment by steakunderscore** [comment]
See: https://github.com/twe4ked/dotfiles/pull/6

**Comment by twe4ked** [comment]
Awesome, thanks very much! I don't currently have a laptop (stolen :() so I can't do much with it at the moment but I'll merge it as soon as I get set back up. Thanks again :)

**Comment by steakunderscore** [comment]
Ah, gutting! Hope you had everything backed up!

**Comment by twe4ked** [comment]
Thanks again. I tried this on my girlfriends laptop and it works great. :+1:
