### ISSUE TITLE
Broken escaping (maybe)

### ISSUE THREAD

**Issue by steakunderscore** [twe4ked/dotfiles#8]
I think there's a bug in your tmux functions. But I'm not sure about this one, so feel free to correct me if I'm wrong.

I can't work out why the `$` symbol is escaped to be `\$` on lines [tmux.sh#L60](https://github.com/twe4ked/dotfiles/blob/master/shell/functions/tmux.sh#L60) and [tmux.sh#L63](https://github.com/twe4ked/dotfiles/blob/master/shell/functions/tmux.sh#L63). I found this was overwriting the `preexec_functions` variable, rather than adding to it.

I think the following code:

``` bash
[[ -z \$precmd_functions ]] && precmd_functions=()
precmd_functions=(\$precmd_functions _tmux_precmd)

[[ -z \$preexec_functions ]] && preexec_functions=()
preexec_functions=(\$preexec_functions _tmux_preexec)
```

should actually read:

``` bash
[[ -z \$precmd_functions ]] && precmd_functions=()
precmd_functions=($precmd_functions _tmux_precmd)

[[ -z \$preexec_functions ]] && preexec_functions=()
preexec_functions=($preexec_functions _tmux_preexec)
```

I don't actually use tmux, so not going to fix (sorry), but noticed it so thought it would be best to let you know.

**Comment by twe4ked** [comment]
Good catch, thanks! I ended up switching to a proper API too which seems nicer.

**Comment by steakunderscore** [comment]
Heh, no problem. Glad I can give a little back :)
